var last_product_id=0;var reviewer_id=0;var admin_ids=new Array();var type='product';var next_page=true;var page=0;var status_check_count=0;var status_check_time=10000;var voucher_left_t;var current_load_url="";$(function(){$('#productModal').on('hide.bs.modal',function(e){if(typeof countdown!='undefined')clearInterval(countdown);});});function show(){$('#sendEmailModal').modal('show');}
function searchProduct(){var search=$('#filters input[name=filter-search]').val();var search_previous=$('#filters input[name=filter-search-previous]').val();if($('#filters input[name=filter-best-discounts]').length){var best_discounts=$('#filters input[name=filter-best-discounts]').is(':checked');}
else var best_discounts="false";var domain=$('#filters select[name=filter-domain]').val();var product_group=$('#filters input[name=filter-product-group]').val();var sort=$('#filters select[name=filter-sort]').val();setCookie('d2018',domain,365);var param={domain:domain,product_group:product_group,sort:sort,search:search,best_discounts:best_discounts,from:'search'};var paramStr="";$.each(param,function(i){paramStr+="&"+i+"="+encodeURIComponent(this);});var url="search/index";if(paramStr)url+="?"+paramStr.substr(1);var urls="feature/index";if(paramStr)urls+="?"+paramStr.substr(1);if(search==''&&product_group==''&&best_discounts==false&&sort=='Default ranking'&&(domain=='www.amazon.com'||domain=='www.amazon.de'||domain=='www.amazon.co.uk')){home_feature_deal(domain);}else{$('.feature-container').hide();$('#home-hr-line').hide();}
$('#next-page-url').val(url);fbq('track','Search',{search_string:search});next_page_products(1);}
//function home_feature_deal(domain){urls="search/feature-deal?domain="+domain;$.ajax({url:urls,method:'GET',cache:false,async:true,success:function(html){if(html==''){$('.feature-container').hide();$('#home-hr-line').hide();}else{$('.feature-container').show();$('#home-hr-line').show();$('.feature-container .feature-box-list').html(html);$('.owl-carousel').owlCarousel({nav:true,loop:true,autoplay:true,autoplayHoverPause:true,autoplayTimeout:5000,slideBy:8,responsive:{1:{items:1},500:{items:1},750:{items:2},1000:{items:3},1250:{items:4},1500:{items:5},1750:{items:6},2000:{items:7},2250:{items:8}}});}}});}
function home_coming_soon(domain){urls="main/coming-soon?domain="+domain;$.ajax({url:urls,method:'GET',cache:false,async:true,success:function(html){if(html==''){$('.feature-container').hide();$('#home-hr-line').hide();}else{$('.feature-container .feature-box-list').html(html);}}});}
function get_ids(){status_check_count=status_check_count+1;if(status_check_count<5){status_check_time=5000;}else if(status_check_count>5&&status_check_count<20){status_check_time=10000;}else{status_check_time=30000;}
var topMenus=getClass('div','box');var f_deals=$("[name='featured_deals']")
var ids=[];var f_ids=[];for(var i=0;i<topMenus.length;i++){ids[i]=topMenus[i].getAttribute('id').slice(8);}
ids=ids.slice(-210);for(var a=0;a<f_deals.length;a++){f_ids[a]=f_deals[a].getAttribute('data-id');}
//f_ids=f_ids.slice(-210);$.ajax({url:"main/judgeinvalid",method:'post',cache:false,data:{ids:ids},success:function(data){data=JSON.parse(data);if(data){for(var i=0;i<data.length;i++){var product_id=data[i]['product_id'];var p_id=data[i]['p_id'];var vouchers_remaining=0;if(data[i]['vouchers_remaining']<=0){vouchers_remaining=0;product_id=p_id;}else{vouchers_remaining=data[i]['vouchers_remaining'];}
//$('#product_'+product_id).css('pointer-events','none');$('#product_'+product_id).addClass('forbidden');$('#product_'+product_id+' .product-image').removeAttr('onclick');$('#product_'+product_id+' .img-container a').attr('href','javascript:void(0)');$('#product_'+product_id+' .title-container a').attr('href','javascript:void(0)');$('#product_'+product_id+'  a').attr('href','javascript:void(0)');$('#product_'+product_id+' .review_btn_'+product_id).removeAttr('onclick');$('#product_'+product_id+' .review_btn_'+product_id).css('background-color','#ccc');$('#product_'+product_id+' .review_btn_'+product_id).html('Out Of Vouchers');$('.text'+p_id).html(vouchers_remaining+' vouchers left');}}}});$.ajax({url:"main/judgeinvalid",method:'post',cache:false,data:{ids:f_ids},success:function(data){data=JSON.parse(data);if(data){for(var i=0;i<data.length;i++){var product_id=data[i]['product_id'];var p_id=data[i]['p_id'];var vouchers_remaining=0;if(data[i]['vouchers_remaining']<=0){vouchers_remaining=0;product_id=p_id;}else{vouchers_remaining=data[i]['vouchers_remaining'];}
$('.review_btn_'+product_id).removeAttr('onclick');$('.feature_deal_a_'+product_id).children("a").removeAttr('href');$('.review_btn_'+product_id).css('background-color','#ccc');$('.text_'+p_id).html(vouchers_remaining+' vouchers left');}}}});if(status_check_count<30){voucher_left_t=window.setTimeout(get_ids,status_check_time);}}
function getClass(tagName,className)
{var tags=$('#box-container-inner>div');var tagArr=[];for(var i=0;i<tags.length;i++){if($(tags[i]).hasClass(className)&&!$(tags[i]).hasClass("forbidden")){tagArr[tagArr.length]=tags[i];}}
return tagArr;}
function show_page(){$(".page-0.nextpage").removeClass("nextpage").addClass("box");refresh_layout();}
function next_page_products(reload){$("#loading-wait").show();if(reload){$('#box-container-inner').html('');$('#box-container').css('height','300px');$('#box-container-inner').css('height','0');$('#loading-notify').hide();var firstUrl=$('#next-page-url').val();if(firstUrl!=''){$.ajax({url:firstUrl,method:'GET',dataType:'json',cache:false,async:true,error:function(XMLHttpRequest,textStatus,errorThrown){current_load_url='';},success:function(data){showProductDetails(data);show_page();window.clearTimeout(voucher_left_t);status_check_count=1;voucher_left_t=window.setTimeout(get_ids,100);var nextPageUrl=$('#next-page-url').val();if(nextPageUrl!=''&&current_load_url==''){current_load_url=nextPageUrl;$.ajax({url:nextPageUrl,method:'GET',dataType:'json',cache:false,async:true,error:function(XMLHttpRequest,textStatus,errorThrown){current_load_url='';},success:function(data){showProductDetails(data);current_load_url='';}});}else if(nextPageUrl==''){$('#loading-wait').hide();$('#loading-notify').show();}}});}}else{show_page();var nextPageUrl=$('#next-page-url').val();if(nextPageUrl!=''&&current_load_url==''){current_load_url=nextPageUrl;$.ajax({url:nextPageUrl,method:'GET',dataType:'json',cache:false,async:true,error:function(XMLHttpRequest,textStatus,errorThrown){current_load_url='';},success:function(data){showProductDetails(data);current_load_url='';}});}else if(nextPageUrl==''){$('#loading-wait').hide();$('#loading-notify').show();}}}
function showProductDetails(data){obj=data;if(obj.code==200){var products=new Array();products=obj.data.products;for(var x in products){if(products[x]['voucher_limit']==0){var product=new Array();product=products[x];var title=product['art_name']
var data="<div class='page-"+page+" nextpage' id='product_"+product['product_id']+"'>"+
"<div class='img-container'>"+
"<a href='product/"+product['product_id']+"?from=index_"+page+"' title='"+title.replace(/'/,'"')+"' target='_blank'> <img class='product-image' src='"+product['image_large']+"' onclick='review_product("+product['product_id']+")' /> </a>"+
"<p class='text"+product['product_id']+" voucher-left'></p>";data+="</div>";data+="<div class='title-container'><a href='product/"+product['product_id']+"?from=index_"+page+"' title='"+title.replace(/'/,'"')+"' target='_blank'> <p class='title' onclick='review_product("+product['product_id']+")'>"+product['art_name']+"</p></a><p class='product-group'><img class='flag' src='"+product['flag']+"'>"+product['product_group']+"</p></div>";data+="<div class='price-box'><span class='price'>";if(product['final_price']<=0){data+="FREE";}else{data+=product['currency_sign']+product['final_price'];}
data+="</span>";if(product['price']>0){data+=" <span class='currency'>"+product['currency']+"</span>";}
if((product['fba']=="AMZ")||(product['fba']=="FBA")){data+="<p class='shipping'>Fulfilled by Amazon</p>";}else if(product['shipping']==0){data+="<p class='shipping'>Free Shipping</p>";}else if(product['shipping']==""){data+="<p class='shipping'>shipping</p>";}else{data+=" <p class='shipping'>"+product['currency_sign']+product['shipping']+" shipping</p>";}
data+=" <p class='discount'>"+product['discount_display']+" off</p></div>";if(product['voucher_limit']!=0){data+=" <p style='height: 88px; padding-top: 55px;'>Voucher limit reached!</p>";}else{data+="<a href='product/"+product['product_id']+"?from=index_"+page+"' target='_blank'> <div class='btn-review review_btn_"+product['product_id']+"' onclick='review_product("+product['product_id']+")'><i class='fa'></i> "+product['button_msg']+"</div> </a>";}
data+="</div>";$('#box-container-inner').append(data);}}
$("#next-page-url").val(obj.data.next_page_url);}else if(obj.code==300){$('#loading').append("<div style='text-align: center; fon t-size: 18px; font-weight: bold; text-shadow: 0 0 10px #fff; padding: 50px 0;'>Something wrong has happened.Reason: "+obj.message+"</div>");}
$(window).scrollTop($(window).scrollTop()-1);refresh_layout();}
$(window).resize(function(){refresh_layout();});function refresh_layout(){$('#wait').hide();var box_height=Array();var final_y=Array();var final_x=Array();$('#box-container-inner .box').each(function(e){box_height.push($(this).height());});var width=$('#box-container').width();var cols=Math.floor(width/250);var start=Math.round((width-cols*250)/2);var container_height=0;jQuery.each(box_height,function(index){var x=start+(index%cols)*250;var row=Math.floor(index/cols);var y=0;for(i=0;i<row;i++){y+=box_height[i*cols+(index%cols)]+14;}
final_y.push(y);final_x.push(x);container_height=y+150;});$('#box-container-inner .box').each(function(index){$(this).css({top:final_y[index],left:final_x[index]});});$('#box-container').height(container_height+370+$('#box-container-inner2').height());$('#box-container-inner').height(container_height+370);}
function review_product(product_id){$('.review_btn_'+product_id+' i').addClass('fa-spinner fa-spin');return true;}
function show_product(product_id){ga('send','event','Deal_home','add_deal',product_id);$('#productModal .modal-body').html('<div style="padding: 20px 20px 0 20px;"><i class="fa fa-spin fa-spinner"></i> Please Wait...</div>');$('#productModal').modal('show');$.ajax({url:"product.php",method:'POST',cache:false,data:{product_id:product_id},success:function(data){$('#productModal .modal-body').html(data);anonymize_links();}});}
function show_last_product(){$('.modal').modal('hide');if(last_product_id>0){show_product(last_product_id);}}
function account(id,from){$('.modal').modal('hide');$('#accountModal .modal-body').html('<i class="fa fa-spin fa-spinner"></i> Please Wait...');$('#accountModal').modal('show');$.ajax({url:"account.php",method:'POST',cache:false,data:{id:id,from:from},success:function(data){$('#accountModal .modal-body').html(data);}});}
function check_account(){$('.modal').modal('hide');$('#accountModal .modal-body').html('<i class="fa fa-spin fa-spinner"></i> Please Wait...');$('#accountModal').modal('show');$('.modal-backdrop').css('background-color','#38c5cb');$('.modal-backdrop.in').css('opacity','0.3');$('.modal-backdrop.in').css('filter','alpha(opacity=30)');$.ajax({url:"account/guide",method:'POST',cache:false,success:function(data){$('#accountModal .modal-body').html(data);}});}
var from='';function sign_in(from){$('#sign-in-form .btn-primary:last').attr('disabled','disabled').html('<i class="fa fa-spin fa-spinner"></i> '+'Please Wait');$.ajax({url:"sign_in.php",method:'POST',cache:false,data:$('#sign-in-form form').serialize(),success:function(data){if(data=="error"){modal_message('Details Incorrect','The email or password you entered was incorrect. Please try again.','Try Again','account("sign-in")');}
else if(data=="signed in"){refresh_menu();$('.modal').modal('hide');$('#postSignInModal').modal('show');if(from=='index'){setTimeout(function(){window.location.reload();},2000);}}
else if(data=="reset password"){window.location.replace("reset_password.php");}
else{modal_message('Email Not Verified','The email address needs verification. <span onclick="resend_confirmation('+data+')" style="text-decoration: underline; cursor: pointer;">Click here</span> to resend verification email.','Sign In Again','account("sign-in")');}}});}
function sign_out(){$('#accountModal .btn').attr('disabled','disabled');$('#accountModal .btn-sign-out').html('<i class="fa fa-spin fa-spinner"></i> Please Wait');$.ajax({url:"sign_out.php",cache:false,success:function(data){$('.modal').modal('hide');refresh_menu();}});}
function create_account(){$('#create-account-form .btn-primary:last').attr('disabled','disabled').html('<i class="fa fa-spin fa-spinner"></i> '+'Please Wait');$.ajax({url:"create_account.php",method:'POST',cache:false,data:$('#create-account-form form').serialize(),success:function(data){$('#create-account-form .btn-primary:last').removeAttr('disabled','disabled').html('Create Account');if(data=="error"){$('#create-account-form .error').html('The email is invalid or password is less than 8 characters.').show();}
else if(data=="email exists"){$('#sign-in-form .error').html('The email you used is already in our system. Please use it to sign in.').show();$('.sign-groups').hide();$('#sign-in-form').show();}
else if(data=="confirmation sent"){$('#sign-in-form .error').html('A confirmation email has been sent to you. Click the link in that email to verify this account before signing in.').show();$('.sign-groups').hide();$('#sign-in-form').show();}
else if(data=="signed in"){refresh_menu();$('.modal').modal('hide');$('#postSignUpModal').modal('show');}}});}
function forgot_password(){var email=$('#forgot-password-form input[name=email]').val();$('#forgot-password-form .btn-primary').attr('disabled','disabled').html('<i class="fa fa-spin fa-spinner"></i> Please Wait');$.ajax({url:"forgot_password.php",method:'POST',cache:false,data:$('#forgot-password-form form').serialize(),success:function(data){$('#forgot-password-form .btn-primary').removeAttr('disabled','disabled').html('Reset Password');if(data=="password reset"){modal_message('Email Sent!','Instructions on resetting your password have been emailed to you.<br><br>Also, check your spam folder for this email. Sometimes it accidentally ends up there.','OK, Thanks!','');}
else modal_message('Invalid Email','The email you entered is invalid. Are you sure you typed it correctly?<br><br><strong>'+email+'</strong>','Try Again','account("forgot-password")');}});}
var from=null;function refresh_menu(from){$.ajax({url:"main/menu",method:'GET',cache:false,data:{ajax:1,from:from},success:function(data){$('.nav.nav-main .menu-top').html(data);}});}
function account_update(){var email=$('#accountModal #sign_email').val();if(check_email(email)){alert("Invalid Email.");return false;}
var password=$('#accountModal #sign_password').val();if((password.length>0)&&(password.length<8)){alert("Password must be longer than 8 characters.");return false;}
$('#account-form .btn-primary').attr('disabled','disabled').html('<i class="fa fa-spin fa-spinner"></i> Please Wait');$.ajax({url:"account_update_check.php",method:'POST',cache:false,data:$('#account-form form').serialize(),success:function(data){$('#account-form .btn-primary').removeAttr('disabled','disabled').html('Update Details');if(data!=""){alert(data);return;}
$.ajax({url:"account_update.php",method:'POST',cache:false,data:$('#account-form form').serialize(),success:function(data){$('#account-form .btn-primary').removeAttr('disabled','disabled').html('Update Details');if(data!=""){modal_message("Oh no!",data,'','');}
else{show_last_product();}}});}});}
function check_profile_url(){var profile_url=$('#sign_profile').val().trim();$('#sign_profile').val(profile_url);if(profile_url.indexOf("http")!=0)profile_url="http://"+profile_url;window.open(profile_url);}
function check_email(email){email=email.trim();var error=0;if(email.match(/^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/ig)===null)error=1;if(email.match(/\.\./)!==null)error=1;if(email.charAt(0)==".")error=1;if(email.split("@").length-1!=1)error=1;else{var parts=email.split("@");if(parts[0].charAt(parts[0].length-1)==".")error=1;if(parts[1].charAt(parts[1].length-1)=="-")error=1;if(parts[1].charAt(0)=="-")error=1;}
return error;}
function mc_subscribe(cl){var email=$('.'+cl+' input[name=email]').val();$('.'+cl+' button').html('<i class="fa fa-spin fa-spinner"></i> Please Wait').attr('disabled','disabled');$.ajax({url:"mc_subscribe.php",method:'POST',cache:false,data:{email:email},success:function(data){$('.'+cl).html(data);}});}
function modal_message(title,message,button,onclick){$('.modal').modal('hide');$('#messageModal .modalName').html(title);$('#messageModal .modal-body').html(message);if(button=='')$('#messageModal .modal-footer').hide();else{$('#messageModal .modal-footer').show();$('#messageModal .modal-footer .btn').html(button).show();$('#messageModal .modal-footer .btn').attr('onclick',onclick);}
$('#messageModal').modal('show');}
function resend_confirmation(reviewer_id){$('.modal').modal('hide');$('#accountModal .modal-body').html('<i class="fa fa-spin fa-spinner"></i> Please Wait...');$('#accountModal').modal('show');$.ajax({url:"resend_confirmation.php",method:'POST',cache:false,data:{reviewer_id:reviewer_id},success:function(data){$.ajax({url:"account.php",method:'POST',cache:false,data:{id:'sign-in'},success:function(data){$('#accountModal .modal-body').html(data);$('#accountModal .modal-body .error').html('A verification email has been sent to you. Click the link in that email to verify your account before signing in.').show();}});}});}
function update_product_groups(){var product_groups=[];$('#productGroupModal .product-group-option.selected').each(function(){product_groups.push($(this).html());});if(product_groups.length>0){$('div[name=filter-product-group]').html(product_groups.join(', '));}
else $('div[name=filter-product-group]').html('All Products');$('#filters input[name=filter-product-group]').val(product_groups.join('*'));}
function show_report_seller_product(product_id){$('#reportSellerProductPageModal .report-form').show();$('#reportSellerProductPageModal .thank-you').hide();$('#reportSellerProductPageModal textarea[name=report_reason]').val('');$('#reportSellerProductPageModal select[name=report_reason]').val('Select Report Reason...');$('#reportSellerProductPageModal input[name=product_id]').val(product_id);$('#reportSellerProductPageModal').modal('show');}
function report_seller_product_send(){if($('#reportSellerProductPageModal select[name=report_reason]').val()=='Select Report Reason...'){alert("Please select a report reason.");return;}
$('#reportSellerProductPageModal .modal-footer .btn-primary').attr('disabled',true).html('<i class="fa fa-spin fa-spinner"></i> Please Wait');$.ajax({url:"report_seller_product.php",method:'POST',cache:false,data:{product_id:$('#reportSellerProductPageModal input[name=product_id]').val(),report_reason:$('#reportSellerProductPageModal textarea[name=report_reason]').val(),report_reason_group:$('#reportSellerProductPageModal select[name=report_reason]').val()},success:function(data){$('#reportSellerProductPageModal .modal-footer .btn-primary').attr('disabled',false).html('Submit Report');$('.modal').modal('hide');modal_message('Your Report Is Lodged!','We will take this matter up with the seller. Thank you for making this site better!','OK','');}});}
function setCookie(name,value,days)
{var exp=new Date();exp.setTime(exp.getTime()+days*24*60*60*1000);document.cookie=name+"="+value+";expires="+exp.toGMTString()+';domain=.vipon.com;path=/';}
function getCookie(c_name){if(document.cookie.length>0){c_start=document.cookie.indexOf(c_name+"=");if(c_start!=-1){c_start=c_start+c_name.length+1;c_end=document.cookie.indexOf(";",c_start);if(c_end==-1)c_end=document.cookie.length;return unescape(document.cookie.substring(c_start,c_end));}}
return "";}
function delCookie(name)
{var exp=new Date();exp.setTime(exp.getTime()-1);var cval=getCookie(name);if(cval!=null)
document.cookie=name+"="+cval+";expires="+exp.toGMTString();}